export const PayfortStatusCodes = {
  '00': { EN: 'Invalid Request', AR: 'Invalid Request' },
  '01': { EN: 'Order Stored', AR: 'Order Stored' },
  '02': { EN: 'Authorization Success', AR: 'Authorization Success' },
  '03': { EN: 'Authorization Failed', AR: 'Authorization Failed' },
  '04': { EN: 'Capture Success', AR: 'Capture Success' },
  '05': { EN: 'Capture failed', AR: 'Capture failed' },
  '06': { EN: 'Refund Success', AR: 'Refund Success' },
  '07': { EN: 'Refund Failed', AR: 'Refund Failed' },
  '08': { EN: 'Authorization Voided Successfully', AR: 'Authorization Voided Successfully' },
  '09': { EN: 'Authorization Void Failed', AR: 'Authorization Void Failed' },
  '10': { EN: 'Incomplete', AR: 'Incomplete' },
  '11': { EN: 'Check status Failed', AR: 'Check status Failed' },
  '12': { EN: 'Check status success', AR: 'Check status success' },
  '13': { EN: 'Purchase Failure', AR: 'Purchase Failure' },
  '14': { EN: 'Purchase Success', AR: 'Purchase Success' },
  '15': { EN: 'Uncertain Transaction', AR: 'Uncertain Transaction' },
  '17': { EN: 'Tokenization failed', AR: 'Tokenization failed' },
  '18': { EN: 'Tokenization success', AR: 'Tokenization success' },
  '19': { EN: 'Transaction pending', AR: 'Transaction pending' },
  '20': { EN: 'On hold', AR: 'On hold' },
  '21': { EN: 'SDK Token creation failure', AR: 'SDK Token creation failure' },
  '22': { EN: 'SDK Token creation success', AR: 'SDK Token creation success' },
  '23': {
    EN: 'Failed to process Digital Wallet service',
    AR: 'Failed to process Digital Wallet service'
  },
  '24': {
    EN: 'Digital wallet order processed successfully',
    AR: 'Digital wallet order processed successfully'
  },
  '27': { EN: 'Check card balance failed', AR: 'Check card balance failed' },
  '28': { EN: 'Check card balance success', AR: 'Check card balance success' },
  '29': { EN: 'Redemption failed', AR: 'Redemption failed' },
  '30': { EN: 'Redemption success', AR: 'Redemption success' },
  '31': {
    EN: 'Reverse Redemption transaction failed',
    AR: 'Reverse Redemption transaction failed'
  },
  '32': {
    EN: 'Reverse Redemption transaction success',
    AR: 'Reverse Redemption transaction success'
  },
  '40': { EN: 'Transaction In review', AR: 'Transaction In review' },
  '42': { EN: 'Currency conversion success', AR: 'Currency conversion success' },
  '43': { EN: 'Currency conversion failed', AR: 'Currency conversion failed' },
  '44': { EN: '3ds success', AR: '3ds success' },
  '45': { EN: '3ds failed', AR: '3ds failed' },
  '46': { EN: 'Bill creation success', AR: 'Bill creation success' },
  '47': { EN: 'Bill creation failed', AR: 'Bill creation failed' },
  '48': {
    EN: 'Generating invoice payment link success',
    AR: 'Generating invoice payment link success'
  },
  '49': {
    EN: 'Generating invoice payment link failed',
    AR: 'Generating invoice payment link failed'
  },
  '50': { EN: 'Batch file upload successfully', AR: 'Batch file upload successfully' },
  '51': { EN: 'Upload batch file failed', AR: 'Upload batch file failed' },
  '52': { EN: 'Token created successfully', AR: 'Token created successfully' },
  '53': { EN: 'Token creation failed', AR: 'Token creation failed' },
  '54': { EN: 'Get Tokens Success', AR: 'Get Tokens Success' },
  '55': { EN: 'Get Tokens Failed', AR: 'Get Tokens Failed' },
  '56': { EN: 'Reporting Request Success', AR: 'Reporting Request Success' },
  '57': { EN: 'Reporting Request Failed', AR: 'Reporting Request Failed' },
  '58': { EN: 'Token updated successfully', AR: 'Token updated successfully' },
  '59': { EN: 'Token updated failed', AR: 'Token updated failed' },
  '62': { EN: 'Get Installment Plans Successfully', AR: 'Get Installment Plans Successfully' },
  '63': { EN: 'Get Installment plans Failed', AR: 'Get Installment plans Failed' },
  '66': { EN: 'Delete Token Success', AR: 'Delete Token Success' },
  '70': { EN: 'Get batch results successfully', AR: 'Get batch results successfully' },
  '71': { EN: 'Get batch results failed', AR: 'Get batch results failed' },
  '72': { EN: 'Batch processing success', AR: 'Batch processing success' },
  '73': { EN: 'Batch processing failed', AR: 'Batch processing failed' },
  '74': { EN: 'Bank transfer successfully', AR: 'Bank transfer successfully' },
  '75': { EN: 'Bank transfer failed', AR: 'Bank transfer failed' },
  '76': { EN: 'Batch validation successfully', AR: 'Batch validation successfully' },
  '77': { EN: 'Batch validation failed', AR: 'Batch validation failed' },
  '80': { EN: 'Credit card verified successfully', AR: 'Credit card verified successfully' },
  '81': { EN: 'Failed to verify credit card', AR: 'Failed to verify credit card' }
};
